###############################################################################
# Ansible Config
#ansible_python_interpreter: /usr/bin/python3
locale_lc_all:        en_US.UTF-8
locale_lang:          en_US.UTF-8

###############################################################################
# General Config
admin_user:           admin                           # Administration user for all hosts
admin_password:       admin                           # Admin user password
