---
###############################################################################
# {%= name %} ansible master playbook                                          #
# Usage:                                                                      #
# ansible-playbook -i environments/dev.inv site.yml                           #
###############################################################################
- import_playbook: playbooks/common.yml
