---
###############################################################################
# {%= name %} ansible master playbook                                         #
# Usage:                                                                      #
# vagrant up                                                                  #
###############################################################################
- hosts: all
  roles:
    - capitanh.common_ansible_role
