# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = '{%= box %}'
  config.vm.hostname = '{%= hostname %}.{%= domain %}'
  config.vm.network 'forwarded_port', guest: 9443, host: 9443
  config.vm.network 'forwarded_port', guest: 9763, host: 9763
  config.vm.provider 'virtualbox' do |vb|
    vb.name = '{%= vbname %}'
    vb.memory = 2048
    vb.cpus = 2
    vb.gui = false
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = 'site.yml'
    ansible.galaxy_role_file = 'requirements.yml'
    ansible.galaxy_roles_path = '~/.ansible/roles'
  end
end
